name: Build JavaFX App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build .deb on Linux
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build .deb package
        run: ./gradlew :app:jpackage

      - name: Upload .deb as artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: app/build/jpackage/*.deb

  build-windows:
    runs-on: windows-latest
    name: Build .exe on Windows
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle wrapper
        run: ./gradlew.bat :app:jpackage

      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: app\build\jpackage\*.exe
